General:
  DumpDir: "/outputs/TestConfig/"
  RunProcessor: True
  LogLevel: 3 # 0: ERRORS, 1: WARNINGS, 2: INFO (default), 3: DEBUG
  NTuplesDirs: ['/eos/atlas/atlascerngroupdisk/phys-higgs/HSG8/tH_v34_minintuples_v3/mc16a_nom/',
                '/eos/atlas/atlascerngroupdisk/phys-higgs/HSG8/tH_v34_minintuples_v3/mc16d_nom/',
                '/eos/atlas/atlascerngroupdisk/phys-higgs/HSG8/tH_v34_minintuples_v3/mc16e_nom/',
                '/eos/atlas/atlascerngroupdisk/phys-higgs/HSG8/tH_v34_minintuples_v3_1/data_nom/']
  MCWeight:
    - 'mc_weight'
    - ['xsec_weight','weight_mc','weight_pileup','weight_bTagSF_DL1r_Continuous','weight_jvt','weight_forwardjvt','weight_leptonSF','runNumber','totalEventsWeighted']
  SkipNomRescale: False # Nominal re-scaling should be added automatically by default

Variables:
  1D:
      - Name: new_bdt_tH
        Label: 'NewBDT(tH)'
        Method:
          - 'bdt_tH'
          - ['BDT']
        Binning: [0, 0.3528, 0.6, 0.78, 1]

      - Name: new_bdt_ttb
        Label: 'NewBDT(ttb)'
        Method:
          - 'bdt_ttb'
          - ['BDT']
        Binning: [0, 0.2, 0.4, 0.6, 0.8, 1]

      - Name: alt_bdt_tH
        Label: 'AltBDT(tH)'
        Method:
          - 'bdt_tH'
          - ['BDT_alt']
        Binning: [0, 0.346, 0.593, 0.786, 1]

      - Name: alt_bdt_ttb
        Label: 'AltBDT(ttb)'
        Method:
          - 'bdt_ttb'
          - ['BDT_alt']
        Binning: [0, 0.2, 0.4, 0.6, 0.8, 1]

samples:
  - Name: tH
    Label: 'tHjb'
    Type: 'SIG'
    NTuplesDirs: null  # Can override the global NTuplesDirs here
    NtuplesRgxs: ['346676*']
    Selection:
      - leptight_cut          # From a replacement file
      - ['leptons_PLIVtight']
    Weight: null  # Here can overwrite the global MCWeight
    Color: '#e6194b'
    RefMC: False  # Should this sample be used as a reference in MC/MC plots

  - Name: tWH
    Label: 'tWHjb'
    Type: 'SIG'
    NTuplesDirs: null
    NtuplesRgxs: ['346678*']
    Selection:
      - leptight_cut
      - ['leptons_PLIVtight']
    Weight: null
    Color: '#3cb44b'
    RefMC: False

  - Name: ttb
    Label: '$t\bar{t}+\geq1b$'
    Type: 'BKG'
    NTuplesDirs: null
    NtuplesRgxs: ['410470_user*']
    Selection: ttb_cut
    Weight: null
    Color: '#e6beff'
    RefMC: False

  - Name: ttb_hdamp_m3top
    Label: '$t\bar{t}+\geq1b$ (hdamp)'
    Type: 'BKG'
    NTuplesDirs: null
    NtuplesRgxs: ['410480_AFII*', '410482_AFII*']
    Selection: ttb_cut
    Weight: null
    Color: '#e6194b'
    RefMC: False

  - Name: ttb_AFII
    Label: '$t\bar{t}+\geq1b$ (AFII)'
    Type: 'BKG'
    NTuplesDirs: null
    NtuplesRgxs: ['410470_AFII*']
    Selection: ttb_cut
    Weight: null
    Color: '#e6beff'
    RefMC: True

  - Name: ttc
    Label: '$t\bar{t}+\geq1c$'
    Type: 'BKG'
    NTuplesDirs: null
    NtuplesRgxs: ['410470_user*']
    Selection: ttc_cut
    Weight: null
    Color: '#000075'
    RefMC: False

  - Name: ttlight
    Label: '$t\bar{t}+\geq0l$'
    Type: 'BKG'
    NTuplesDirs: null
    NtuplesRgxs: ['410470_user*']
    Selection: ttl_cut
    Weight: null
    Color: '#4363d8'
    RefMC: False

  - Name: ttlight_AFII
    Label: '$t\bar{t}+\geq0l$ (AFII)'
    Type: 'BKG'
    NTuplesDirs: null
    NtuplesRgxs: ['410470_AFII*']
    Selection: ttl_cut
    Weight: null
    Color: '#000075'
    RefMC: True

  - Name: ttlight_aMCH7
    Label: '$t\bar{t}+\geq0l$ (aMC@H7)'
    Type: 'BKG'
    NTuplesDirs: null
    NtuplesRgxs: ['412116_AFII*', '412117_AFII*']
    Selection: ttl_cut
    Weight: null
    Color: '#3cb44b'
    RefMC: False

  - Name: ttlight_PH7
    Label: '$t\bar{t}+\geq0l$ (Pow@H7)'
    Type: 'BKG'
    NTuplesDirs: null
    NtuplesRgxs: ['411233_AFII*', '411234_AFII*']
    Selection: ttl_cut
    Weight: null
    Color: '#911eb4'
    RefMC: False

  - Name: ttH
    Label: '$t\bar{t}+H$'
    Type: 'BKG'
    NTuplesDirs: null
    NtuplesRgxs: ['346343_user*', '346344_user*', '346345_user*']
    Selection:
      - leptight_cut
      - ['leptons_PLIVtight']
    Weight: null
    Color: '#911eb4'
    RefMC: False

  - Name: ttZ
    Label: '$t\bar{t}+Z$'
    Type: 'BKG'
    NTuplesDirs: null
    NtuplesRgxs: ['410156_user*', '410157_user*', '410218_user*', '410219_user*', '410220_user*']
    Selection:
      - leptight_cut
      - ['leptons_PLIVtight']
    Weight: null
    Color: '#46f0f0'
    Category: 'ttV'
    RefMC: False

  - Name: ttW
    Label: '$t\bar{t}+W$'
    Type: 'BKG'
    NTuplesDirs: null
    NtuplesRgxs: ['412123_user*', '410155_user*']
    Selection:
      - leptight_cut
      - ['leptons_PLIVtight']
    Weight: null
    Color: '#f032e6'
    Category: 'ttV'
    RefMC: False

  - Name: tZq
    Label: 'tZq'
    Type: 'BKG'
    NTuplesDirs: null
    NtuplesRgxs: ['410560_user*']
    Selection:
      - leptight_cut
      - ['leptons_PLIVtight']
    Weight: null
    Color: '#bcf60c'
    Category: 'Minor'
    RefMC: False

  - Name: tWZ
    Label: 'tWZ'
    Type: 'BKG'
    NTuplesDirs: null
    NtuplesRgxs: ['410408*']
    Selection:
      - leptight_cut
      - ['leptons_PLIVtight']
    Weight: null
    Color: '#fabebe'
    Category: 'Minor'
    RefMC: False

  - Name: singletop_Wtchannel
    Label: 't (s-chan)'
    Type: 'BKG'
    NTuplesDirs: null
    NtuplesRgxs: ['410646_user*', '410647_user*']
    Selection:
      - leptight_cut
      - ['leptons_PLIVtight']
    Weight: null
    Color: '#008080'
    Category: 'Single-top'
    RefMC: False

  - Name: singletop_tchan
    Label: 't (t-chan)'
    Type: 'BKG'
    NTuplesDirs: null
    NtuplesRgxs: ['410658_user*', '410659_user*']
    Selection:
      - leptight_cut
      - ['leptons_PLIVtight']
    Weight: null
    Color: '#f58231'
    Category: 'Single-top'
    RefMC: False

  - Name: singletop_schannel
    Label: 'tW'
    Type: 'BKG'
    NTuplesDirs: null
    NtuplesRgxs: ['410644_user*', '410645_user*']
    Selection:
      - leptight_cut
      - ['leptons_PLIVtight']
    Weight: null
    Color: '#9a6324'
    Category: 'Single-top'
    RefMC: False

  - Name: Wjets
    Label: 'W+jets'
    Type: 'BKG'
    NTuplesDirs: null
    NtuplesRgxs: ['364156*', '364159*', '364162*', '364165*', '364170*', '364173*', '364176*', '364179*', '364184*', '364187*', '364190*', '364193*', '364157*', '364160*', '364163*', '364166*', '364171*', '364174*', '364177*', '364180*', '364185*', '364188*', '364191*', '364194*', '364158*', '364161*', '364164*', '364167*', '364172*', '364175*', '364178*', '364181*', '364186*', '364189*', '364192*', '364195*', '364168*', '364169*', '364182*', '364183*', '364196*', '364197*']
    Selection:
      - leptight_cut
      - ['leptons_PLIVtight']
    Weight: null
    Color: '#fffac8'
    Category: 'V+jets'
    RefMC: False

  - Name: Zjets
    Label: 'Z+jets'
    Type: 'BKG'
    NTuplesDirs: null
    NtuplesRgxs: ['364100*', '364103*', '364106*', '364109*', '364114*', '364117*', '364120*', '364123*', '364128*', '364131*', '364134*', '364137*', '364101*', '364104*', '364107*', '364110*', '364115*', '364118*', '364121*', '364124*', '364129*', '364132*', '364135*', '364138*', '364102*', '364105*', '364108*', '364111*', '364116*', '364119*', '364122*', '364125*', '364130*', '364133*', '364136*', '364139*', '364112*', '364113*', '364126*', '364127*', '364140*', '364141*']
    Selection:
      - leptight_cut
      - ['leptons_PLIVtight']
    Weight: null
    Color: '#800000'
    Category: 'V+jets'
    RefMC: False

  - Name: VV
    Label: 'VV'
    Type: 'BKG'
    NTuplesDirs: null
    NtuplesRgxs: ['364250_user*', '364253_user*', '364254_user*', '364255_user*', '364288_user*', '364289_user*', '364290_user*', '363355_user*', '363356_user*', '363357_user*', '363358_user*', '363359_user*', '363360_user*', '363489_user*', '363494_user*']
    Selection:
      - leptight_cut
      - ['leptons_PLIVtight']
    Weight: null
    Color: '#aaffc3'
    Category: 'Minor'
    RefMC: False

  - Name: otherHiggs
    Label: 'Higgs'
    Type: 'BKG'
    NTuplesDirs: null
    NtuplesRgxs: ['342282*', '342283*', '342284*', '342285*']
    Selection:
      - leptight_cut
      - ['leptons_PLIVtight']
    Weight: null
    Color: '#808000'
    Category: 'Minor'
    RefMC: False

  - Name: raretop
    Label: 'Rare Tops'
    Type: 'BKG'
    NTuplesDirs: null
    NtuplesRgxs: ['304014*', '412043*']
    Selection:
      - leptight_cut
      - ['leptons_PLIVtight']
    Weight: null
    Color: '#ffd8b1'
    Category: 'Minor'
    RefMC: False

  - Name: Fakes
    Label: 'Fakes'
    Type: 'BKG'
    NTuplesDirs: null
    NtuplesRgxs: ['data15*', 'data16*', 'data17*', 'data18*']
    Selection: null
    Weight: mm_weight
    Color: '#ffe119'
    RefMC: False

  - Name: Data
    Label: 'Data'
    Type: 'DATA'
    NTuplesDirs: null
    NtuplesRgxs: ['data15*', 'data16*', 'data17*', 'data18*']
    Selection:
      - leptight_cut
      - ['leptons_PLIVtight']
    Weight: null
    Color: '#808080'
    RefMC: False

Regions:
  - Name: PR
    Label: 'PR'
    Selection:
      - PR_fn
      - ['njets', 'nbjets', 'njets_CBT4', 'njets_CBT5', 'njets_CBT123', 'tau_pt', 'nfwdjets']
    Targets: null

  - Name: CR
    Label: 'CR'
    Selection:
      - CR_fn
      - ['njets', 'nbjets', 'njets_CBT4', 'njets_CBT5', 'njets_CBT123', 'tau_pt', 'nfwdjets']
    Targets: ['ttb']

  - Name: SR
    Label: 'SR'
    Selection:
      - SR_fn
      - ['njets', 'nbjets', 'njets_CBT4', 'njets_CBT5', 'njets_CBT123', 'tau_pt', 'nfwdjets']
    Targets: ['tH', 'tWH']

Rescales:
  - Name: 'ttb_1p25'
    Label: '$k_{ttb} \times 1.25$'
    Affects: ['ttb']
    Method:
      - ttb_1p25_rescale
      - ['weights']