General:
  DumpDir: "./outputs/TEST/2D_PLOTS_TEST/"
  InputHistos: /eos/user/m/maly/thbb/CoffeaPlot/outputs/TEST/2D_PLOTS_TEST/data/data___nominal_Loose.pkl
  Helpers: '/eos/user/m/maly/thbb/CoffeaPlot/configs/config_helper.py'
  Trees: 'nominal_Loose'
  RunProcessor: True
  RunPlotter: True
  LogLevel: 2
  NTuplesDirs: ['/eos/atlas/atlascerngroupdisk/phys-higgs/HSG8/tH_v34_minintuples_v3/mc16a_nom/',
                '/eos/atlas/atlascerngroupdisk/phys-higgs/HSG8/tH_v34_minintuples_v3/mc16d_nom/',
                '/eos/atlas/atlascerngroupdisk/phys-higgs/HSG8/tH_v34_minintuples_v3/mc16e_nom/',
                '/eos/atlas/atlascerngroupdisk/phys-higgs/HSG8/tH_v34_minintuples_v3_1/data_nom/']
  MCWeight:
    - 'MC_weight'
    - ['xsec_weight','weight_mc','weight_pileup','weight_bTagSF_DL1r_Continuous','weight_jvt','weight_forwardjvt','weight_leptonSF','runNumber','totalEventsWeighted']
  Blinding: 0.00333
  makeplots: ['2D', 'SEPARATION']

Variables:
  2D:
    - Name: tagnonb_topb_m_v_bdt_ttb
      Label:
        - '$M_{j_{light-tag},b_{top}}$'
        - 'AltBDT(ttb)'
      MethodX:
          - x_gev
          - ['tagnonb_topb_m']
      MethodY:
          - bdt_ttb
          - ['BDT_alt']
      Binning:
        - 0,600,50
        - 0,1,40
      InterestingVals:
        - 130
        - 0.4

    - Name: n_tophad_jets_CBT123_ttAll_v_bdt_ttb
      Label:
        - 'Number of Hadornic Top Jets in PCBT 123 (ttAll-$\chi^{2}$)'
        - 'AltBDT(ttb)'
      MethodX:  n_tophad_jets_CBT123_ttAll
      MethodY:
          - bdt_ttb
          - ['BDT_alt']
      Binning:
        - 0,3,3
        - 0,1,40
      InterestingVals:
        - 1
        - 0.4

    - Name: sphericity_v_bdt_ttb
      Label:
        - 'Sphericity'
        - 'AltBDT(ttb)'
      MethodX:  sphericity
      MethodY:
          - bdt_ttb
          - ['BDT_alt']
      Binning:
        - 0,1,30
        - 0,1,40
      InterestingVals:
        - 0.3
        - 0.4

    - Name: chi2_min_tophad_m_v_bdt_ttb
      Label:
        - 'Hadronic Top Mass ($t\bar{t}$-$\chi^{2}$)'
        - 'AltBDT(ttb)'
      MethodX:
        - x_gev
        - ['chi2_min_tophad_m']
      MethodY:
          - bdt_ttb
          - ['BDT_alt']
      Binning:
        - 0,600,50
        - 0,1,40
      InterestingVals:
        - 200
        - 0.4

  1D:
    - Name: tagnonb_topb_m
      Label: '$M_{j_{light-tag},b_{top}}$'
      Method:
          - x_gev
          - ['tagnonb_topb_m']
      Binning:  0,600,50

    - Name: n_tophad_jets_CBT123_ttAll
      Label: 'Number of Hadornic Top Jets in PCBT 123 (ttAll-$\chi^{2}$)'
      Method: n_tophad_jets_CBT123_ttAll
      Binning:  0,3,3

    - Name: sphericity
      Label: 'Sphericity'
      Method: sphericity
      Binning:  0,1,30

    - Name: chi2_min_tophad_m
      Label: 'Hadronic Top Mass ($t\bar{t}$-$\chi^{2}$)'
      Method:
        - x_gev
        - ['chi2_min_tophad_m']
      Binning:  0,600,50

# Samples:

#   - Name: tH
#     Label: 'tHjb'
#     Type: 'SIG'
#     NtuplesRgxs: ['346676*']
#     Selection:
#       - tight_lepton
#       - ['leptons_PLIVtight']
#     Color: '#e6194b'
#     RefMC: True

Supersamples:

  - Name: ttb_5FS
    NtuplesRgxs: ['410470_user*']
    SubSamples:
      # - Name: ttb
      #   Label: '$t\bar{t}+\geq1b$'
      #   Type: 'BKG'
      #   Selection:
      #     - ttb_cut
      #     - ['leptons_PLIVtight','HF_SimpleClassification']
      #   Color: 'orange'

      - Name: ttb_5FS_1b
        Label: '$t\bar{t}+1b$ (5FS)'
        Type: 'BKG'
        Selection:
          - tt1b_cut
          - ['leptons_PLIVtight','HF_Classification']
        Color: 'green'

      - Name: ttb_5FS_1B
        Label: '$t\bar{t}+1B$ (5FS)'
        Type: 'SIG'
        Selection:
          - tt1B_cut
          - ['leptons_PLIVtight','HF_Classification']
        Color: 'green'

      - Name: ttb_5FS_2b
        Label: '$t\bar{t}+2b$ (5FS)'
        Type: 'BKG'
        Selection:
          - ttbb_cut
          - ['leptons_PLIVtight','HF_Classification']
        Color: 'purple'

Regions:
  - Name: CR
    Label: 'CR'
    Selection:
      - CR_ttb_fn
      - ['njets', 'nbjets', 'njets_CBT4', 'njets_CBT5','nalljets', 'njets_CBT0', 'tau_pt', 'nfwdjets']
    Targets: ['ttb']

SEPARATION:
    seploc: [0.5,0.8]

# Histo2D:
#   vline: 130
#   hline: 0.4