General:
  DumpDir: "./outputs/btag_mc_eff/"
  InputHistos: ./outputs/btag_mc_eff/data/data___nominal_Loose.pkl
  Helpers: '/eos/user/m/maly/thbb/CoffeaPlot/configs/config_helper.py'
  Trees: 'nominal_Loose'
  RunProcessor: True
  RunPlotter: True
  LogLevel: 2
  NTuplesDirs: ['/eos/user/m/maly/thbb/NoCutsNomOnly/L1/mc16a/', '/eos/user/m/maly/thbb/NoCutsNomOnly/L1/mc16d/','/eos/user/m/maly/thbb/NoCutsNomOnly/L1/mc16e/']
  MCWeight: 'weight_mc'
  makeplots: ['EFF']

Variables:
  1D:
    - Name: good_jets
      Method:
        - good_jets
        - ["jet_pt", "jet_eta", "jet_truthflavExtended", "jet_truthflav", "jet_tagWeightBin_DL1r_Continuous", "jet_DL1r"]
      Type: "GHOST"

    - Name: good_jets_pcbt
      Method:
        - get_pcbt
        - good_jets
      Type: "GHOST"

    - Name: good_jets_dl1r
      Method:
        - get_dl1r
        - good_jets
      Type: "GHOST"

    - Name: good_jets_truthFlav
      Method:
        - get_truthFlav
        - good_jets
      Type: "GHOST"

    - Name: good_jets_truthFlavExt
      Method:
        - get_truthFlavExt
        - good_jets
      Type: "GHOST"
    - Name: good_jets_pt
      Method:
        - get_pt
        - good_jets
      Type: "GHOST"


    - Name: good_jets_pcbt_0
      Method:
        - obj0_x
        - good_jets_pcbt
      Type: "GHOST"

    - Name: good_jets_dl1r_0
      Method:
        - obj0_x
        - good_jets_dl1r
      Type: "GHOST"

    - Name: good_jets_truthFlav_0
      Method:
        - obj0_x
        - good_jets_truthFlav
      Type: "GHOST"

    - Name: good_jets_truthFlavExt_0
      Method:
        - obj0_x
        - good_jets_truthFlavExt
      Type: "GHOST"

    - Name: good_jets_pt_0
      Method:
        - obj0_x_GeV
        - good_jets_pt
      Type: "GHOST"
Effs:
  1D:
    - Name: b_MC_eff
      Label: 'Jet $p^T$'
      NumSel:
        - b_70_pass_FixedCut
        - ['good_jets_truthFlav','good_jets_dl1r']
      DenomSel:
        - b_truth
        - ['good_jets_truthFlav']
      Method:
        - flatten_x_gev
        - good_jets_pt
      idxby: nonevent
      Binning: 25,300,21

Samples:
  - Name: ttbar
    Label: '$t\bar{t}$'
    Type: 'BKG'
    NtuplesRgxs: ['*410470*/*']
    Selection:
      - at_least_a_jet
      - jet_pt
    Color: 'red'

Regions:
  - Name: Inclusive
    Label: 'Inclusive'
    Selection:
      - INCL_fn
      - ['el_Id_TightLH', 'el_Isol_PLImprovedTight', 'mu_Id_Medium', 'mu_Isol_PLImprovedTight', 'jet_pt']

  # - Name: SR
  #   Label: 'SR'
  #   Selection:
  #     - SR_fn
  #     - ['njets', 'nbjets', 'njets_CBT4', 'njets_CBT5','nalljets', 'njets_CBT0', 'tau_pt', 'nfwdjets']
  #   #Targets: ['tH', 'tWH']

Eff:
  Main:
    YNorm: False
    YRange: [0.6, 1.0]